# -*- coding: utf-8 -*-
"""ETL_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sx9waVceFRkTjGbdOiMi6mOVZuFwsIe

Cell 1 -- Extract
"""

import pandas as pd

users = [
    {'id': 1, 'name': 'Gioconda', 'account': '0001-1', 'card': '**** 1111', 'news': []},
    {'id': 2, 'name': 'Medusa', 'account': '0002-2', 'card': '**** 2222', 'news': []},
    {'id': 3, 'name': 'Cassandra', 'account': '0003-3', 'card': '**** 3333', 'news': []},
]

df = pd.DataFrame(users)
print(df[['id', 'name', 'account', 'card']])

"""Cell 2 -- Transform"""

def generate_message(user):
  return f"{user['name']}, investir é o caminho para o seu futuro financeiro. Comece hoje!"

for user in users:
  message = generate_message(user)
  user['news'].append({'description': message})
  print(message)

"""Call 3 -- Load"""

import json

with open('output.json', 'w', encoding='utf-8') as f:
  json.dump(users, f, ensure_ascii=False, indent=2)

print("Pipeline ETL concluída. Dados salvos em output.json.")